owner: LangbaseInc
repo: langbase-api-status
sites:
  - name: Langbase API
    url: https://api.langbase.com
status-website:
  # cname: demo.upptime.js.org
  baseUrl: /langbase-api-status
  logoUrl: https://avatars.githubusercontent.com/u/151507869?s=88&v=4
  name: Langbase
  navbar:
    - title: Langbase
      href: https://langbase.com
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
