owner: LangbaseInc
repo: status
sites:
  - name: Langbase API
    url: https://api.langbase.com
status-website:
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/LangbaseInc/docs-images/refs/heads/main/langbase/design/langbase.com.png
  name: Langbase
  navbar:
    - title: Langbase
      href: https://langbase.com
    - title: Status
      href: /
    - title: Subscribe on GitHub
      href: https://github.com/$OWNER/$REPO
i18n:
  footer: ''
